spring:
  application:
    name: pcf-route-service

jwk:
  filename: jwk-local-key-set.json

management:
  security:
    enabled: false

security:
  basic:
      enabled: false

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    io.pivotalservices: DEBUG