spring:
  application:
    name: pcf-route-service

management:
  security:
    enabled: false

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    io.pivotalservices: DEBUG
